### ISSUE TITLE
System does go in bootloop when installing Miui 6.6.16 

### ISSUE THREAD

**Issue by wirehub** [redmaner/MIUI8-XML-DUTCH#15] opened 2016-06-19 19:26 UTC
user : Brian Amesz / Michel M on Xiaomi.eu (possible more) are having issues installing Miui 8 with Dutch (nederlands) language . when update is done, it will end up in bootloop causing not installing :-1: 

as said on forum, it seems not ready yet?

**Comment by ingbrzy** [comment] 2016-06-19 19:28
need a logcat to debug it..

**Comment by wirehub** [comment] 2016-06-19 19:31
not sure how to as my phone is not set to english after trying multiple times to install Dutch ,..

**Comment by MannyRibo** [comment] 2016-06-19 19:38
But wait can you tell me the exact situation. Like does it not install at all at first flash? Or flashing works fine, so then you're in the system, shut phone down and upon booting it goes in bootloop? Because if the first flash to MIUI 8 results in bootloop for you I can tell you I updated my mi4 to 6.6.16 just fine (note: not the rebuilt one though, and I made some changes in between the first rom and rebuilt one). If you mean bootloop upon first restart, I didn't check that because I didn't restart it and am back on miui7.

**Comment by redmaner** [comment] 2016-06-19 19:44
So if I get this correctly you flashed MIUI8 and it bootloops at first boot? So the phone has never been booted into MIUI8 yet?

If this is indeed the case the problem is probably not the language

**Comment by MannyRibo** [comment] 2016-06-19 19:45
Because if you clean flash MIUI 8 with wipes and everything how's your phone supposed to know you're Dutch? It will restart with English as default setting. So when this is about the first flash to MIUI 8 it sounds to me like they are just having general installation problems rather than it having anything to do with the Dutch translation. The users just happen to be Dutch and think it has something to do with the translation.

**Comment by wirehub** [comment] 2016-06-19 19:55
flash from Miui 7 6.5.26 in dutch version to Miui8 6.6.16  results in continuous bootloop.
when entering TWRP flashed 6.6.16 , wipe dalwik / cache which result in a working system, but when rebooting it enters bootloop again. 
Tried installing from zero, by format internal mem , cleared cache / system etc and cleared dalvik when 6.6.16 is flashed , getting new installation and working with Dutch language, unfortunately when reboot it results in bootloop again. 
Tried above again but left language in English,  no problems and after reboot still ok. Definitly a dutch language issue I quess for Miui 8

**Comment by ingbrzy** [comment] 2016-06-19 20:01
Which device?
When rebooted? In some specific place like settings or random?

**Comment by redmaner** [comment] 2016-06-19 20:02
That clears things up, but then we definitely need a logcat to find the issue.

Since we switched from MIUI7 to MIUI8 I bet it's a variable too much or too less

**Comment by wirehub** [comment] 2016-06-19 20:07
Mi 5 , from updater app Miui 7 > Miui 8 bootloop

**Comment by ingbrzy** [comment] 2016-06-20 04:13
@wirehub please try this build if issue still exists..

Download:
https://mega.nz/#!y9YhXQyY!qsF_RNfW5U22vNssPGbwOgFJMDQeeqWmBVIJ6I7UaXY

made a few important fixes in dutch translation.. thanks..

**Comment by wirehub** [comment] 2016-06-20 04:25
@ingbrzy i Will check when i get  home from work today. Thx for assisting really appreciated

**Comment by fordrwd4ever** [comment] 2016-06-20 09:41
I have a logcat for you from my Redmi Note 2 
first one is the short version and the second one is more detailed :)
[miui8-dutch.txt](https://github.com/redmaner/MIUI8-XML-DUTCH/files/323094/miui8-dutch.txt)
[miui8-dutch2.txt](https://github.com/redmaner/MIUI8-XML-DUTCH/files/323095/miui8-dutch2.txt)

**Comment by wirehub** [comment] 2016-06-20 10:43
user  Michel M confirms ok in Dutch and no bootloop. 
user Wirehub/  Brian Amesz will test tonight

**Comment by scoutcow** [comment] 2016-06-20 11:06
I can confirm as wel (GilianHettinga @xiaomi.eu)
Installed your new rom on my mi5 and no bootloop with Dutch language anymore. Thanks a lot for this fast solution!

**Comment by fordrwd4ever** [comment] 2016-06-20 11:11
What needs to be replaced in the system to fix the issue?
With ADB you can get full access to the system.
That way it's not necessary to compile a new rom

**Comment by ingbrzy** [comment] 2016-06-20 11:25
@fordrwd4ever all whats edited upper... easier for you is install fixed rom...

closing this issue as solved..

**Closed as completed by ingbrzy** 2016-06-20 11:25 UTC
Labels: bug

**Comment by wirehub** [comment] 2016-06-20 18:15
confirmed ok from Wirehub (Brian Amesz)

**Comment by remcoharmsen** [comment] 2016-06-21 07:27
Confirmed to work now after TWRP flash coming from 7.3.10 in Dutch language. Had bootloop in previous version, now it's fixed!
